version: '3.7'
services:
  manager:
    image: alpine:latest
    tty: true
    volumes:
      - . :/code
  worker1:
    image: nginx
    ports:
      - "8001:80"
  worker2:
    image: nginx
    ports:
      - "8002:80"